apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskmanager
data:
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/taskdb'
  SPRING_DATASOURCE_USERNAME: 'postgres'
