name: CI - Docker Build & Push (Backend + Frontend)

on:
  push:
    branches:
      - master

jobs:
  backend-build-and-push:
    name: Backend - Build & Push
    runs-on: ubuntu-latest
    
    if: |
      github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (backend)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:latest .

      - name: Push Docker image (backend)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:latest

  frontend-build-and-push:
    name: Frontend - Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (frontend)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-frontend:latest ./frontend

      - name: Push Docker image (frontend)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-frontend:latest
